-- MySQL Script generated by MySQL Workbench
-- Wed Oct 27 10:12:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_wakanda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_wakanda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_wakanda` ;
USE `db_wakanda` ;

-- -----------------------------------------------------
-- Table `db_wakanda`.`Tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_wakanda`.`Tema` (
  `id_Tema` BIGINT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  `quantidade_postagens` BIGINT NOT NULL,
  `tendencia_semana` TINYINT NULL,
  PRIMARY KEY (`id_Tema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_wakanda`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_wakanda`.`Usuario` (
  `id_Usuario` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_wakanda`.`Postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_wakanda`.`Postagem` (
  `idPostagem` INT NOT NULL AUTO_INCREMENT,
  `midia` BLOB NULL,
  `texto` VARCHAR(1000) NOT NULL,
  `data` TIMESTAMP NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `curtida` BIGINT NULL,
  `compartilhamento` BIGINT NULL,
  `id_Tema` BIGINT NOT NULL,
  `id_Usuario` BIGINT NOT NULL,
  PRIMARY KEY (`idPostagem`),
  INDEX `fk_Postagem_Tema_idx` (`id_Tema` ASC) VISIBLE,
  INDEX `fk_Postagem_Usuario1_idx` (`id_Usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Postagem_Tema`
    FOREIGN KEY (`id_Tema`)
    REFERENCES `db_wakanda`.`Tema` (`id_Tema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Postagem_Usuario1`
    FOREIGN KEY (`id_Usuario`)
    REFERENCES `db_wakanda`.`Usuario` (`id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
